// Joker 节点间/投递 gRPC 契约。
// 数据流（D02）：deliver worker 消费 chat.push 后经本服务把已落库消息投给持有连接的 CS。
// 取舍：Unary 而非 Stream——消息模型离散，Unary 实现简单、易调试（AGENTS.md §2 记录的取舍）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: joker.proto

package jokerproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Relay_RelayMessage_FullMethodName = "/joker.Relay/RelayMessage"
)

// RelayClient is the client API for Relay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayClient interface {
	// RelayMessage 投递一条已落库消息；目标 CS 查本地连接表写入 Send 通道。
	RelayMessage(ctx context.Context, in *RelayMessageRequest, opts ...grpc.CallOption) (*RelayMessageResponse, error)
}

type relayClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayClient(cc grpc.ClientConnInterface) RelayClient {
	return &relayClient{cc}
}

func (c *relayClient) RelayMessage(ctx context.Context, in *RelayMessageRequest, opts ...grpc.CallOption) (*RelayMessageResponse, error) {
	out := new(RelayMessageResponse)
	err := c.cc.Invoke(ctx, Relay_RelayMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServer is the server API for Relay service.
// All implementations must embed UnimplementedRelayServer
// for forward compatibility
type RelayServer interface {
	// RelayMessage 投递一条已落库消息；目标 CS 查本地连接表写入 Send 通道。
	RelayMessage(context.Context, *RelayMessageRequest) (*RelayMessageResponse, error)
	mustEmbedUnimplementedRelayServer()
}

// UnimplementedRelayServer must be embedded to have forward compatible implementations.
type UnimplementedRelayServer struct {
}

func (UnimplementedRelayServer) RelayMessage(context.Context, *RelayMessageRequest) (*RelayMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelayMessage not implemented")
}
func (UnimplementedRelayServer) mustEmbedUnimplementedRelayServer() {}

// UnsafeRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServer will
// result in compilation errors.
type UnsafeRelayServer interface {
	mustEmbedUnimplementedRelayServer()
}

func RegisterRelayServer(s grpc.ServiceRegistrar, srv RelayServer) {
	s.RegisterService(&Relay_ServiceDesc, srv)
}

func _Relay_RelayMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).RelayMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_RelayMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).RelayMessage(ctx, req.(*RelayMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Relay_ServiceDesc is the grpc.ServiceDesc for Relay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Relay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "joker.Relay",
	HandlerType: (*RelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayMessage",
			Handler:    _Relay_RelayMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "joker.proto",
}
