// Joker 节点间/投递 gRPC 契约。
// 数据流（D02）：deliver worker 消费 chat.push 后经本服务把已落库消息投给持有连接的 CS。
// 取舍：Unary 而非 Stream——消息模型离散，Unary 实现简单、易调试（AGENTS.md §2 记录的取舍）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v7.35.1
// source: joker.proto

package jokerproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId    string `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`            // 服务端消息 ID（幂等键）
	CliMsgId string `protobuf:"bytes,2,opt,name=cli_msg_id,json=cliMsgId,proto3" json:"cli_msg_id,omitempty"` // 客户端消息 ID（发送端 UI 打勾用，经 ack 透传）
	ConvId   string `protobuf:"bytes,3,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	FromUid  string `protobuf:"bytes,4,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	ToUid    string `protobuf:"bytes,5,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"` // 本 CS 上的目标连接
	Type     string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`                // single|group|system_event
	Content  []byte `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`          // 消息内容（JSON 字节）
	Seq      int64  `protobuf:"varint,8,opt,name=seq,proto3" json:"seq,omitempty"`                 // 会话内序号（客户端排序去重键）
	Mention  bool   `protobuf:"varint,9,opt,name=mention,proto3" json:"mention,omitempty"`         // 投递展开后的 @ 标记
	// 防回环保留位（AGENTS.md §2）：Kafka 主干下投递是 worker→CS 单向的，
	// CS 不会再转发消息，恒为 false；保留字段以兼容契约审查。
	IsLocal   bool  `protobuf:"varint,10,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	CreatedAt int64 `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *RelayMessageRequest) Reset() {
	*x = RelayMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_joker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessageRequest) ProtoMessage() {}

func (x *RelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_joker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessageRequest.ProtoReflect.Descriptor instead.
func (*RelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_joker_proto_rawDescGZIP(), []int{0}
}

func (x *RelayMessageRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RelayMessageRequest) GetCliMsgId() string {
	if x != nil {
		return x.CliMsgId
	}
	return ""
}

func (x *RelayMessageRequest) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *RelayMessageRequest) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *RelayMessageRequest) GetToUid() string {
	if x != nil {
		return x.ToUid
	}
	return ""
}

func (x *RelayMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RelayMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *RelayMessageRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RelayMessageRequest) GetMention() bool {
	if x != nil {
		return x.Mention
	}
	return false
}

func (x *RelayMessageRequest) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *RelayMessageRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RelayMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delivered bool   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"` // 是否已写入目标连接的 Send 通道
	Reason    string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`        // 未投递原因：not_found=本机无该连接
}

func (x *RelayMessageResponse) Reset() {
	*x = RelayMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_joker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessageResponse) ProtoMessage() {}

func (x *RelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_joker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessageResponse.ProtoReflect.Descriptor instead.
func (*RelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_joker_proto_rawDescGZIP(), []int{1}
}

func (x *RelayMessageResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *RelayMessageResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_joker_proto protoreflect.FileDescriptor

var file_joker_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6a,
	0x6f, 0x6b, 0x65, 0x72, 0x22, 0xa9, 0x02, 0x0a, 0x13, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x4d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x72,
	0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d,
	0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x4c, 0x0a, 0x14, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x50,
	0x0a, 0x05, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x47, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6c, 0x61,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x29, 0x5a, 0x27, 0x61, 0x6c, 0x66, 0x72, 0x65, 0x64, 0x2e, 0x62, 0x72, 0x61, 0x76, 0x65,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x6a, 0x6f, 0x6b, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_joker_proto_rawDescOnce sync.Once
	file_joker_proto_rawDescData = file_joker_proto_rawDesc
)

func file_joker_proto_rawDescGZIP() []byte {
	file_joker_proto_rawDescOnce.Do(func() {
		file_joker_proto_rawDescData = protoimpl.X.CompressGZIP(file_joker_proto_rawDescData)
	})
	return file_joker_proto_rawDescData
}

var file_joker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_joker_proto_goTypes = []interface{}{
	(*RelayMessageRequest)(nil),  // 0: joker.RelayMessageRequest
	(*RelayMessageResponse)(nil), // 1: joker.RelayMessageResponse
}
var file_joker_proto_depIdxs = []int32{
	0, // 0: joker.Relay.RelayMessage:input_type -> joker.RelayMessageRequest
	1, // 1: joker.Relay.RelayMessage:output_type -> joker.RelayMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_joker_proto_init() }
func file_joker_proto_init() {
	if File_joker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_joker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_joker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_joker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_joker_proto_goTypes,
		DependencyIndexes: file_joker_proto_depIdxs,
		MessageInfos:      file_joker_proto_msgTypes,
	}.Build()
	File_joker_proto = out.File
	file_joker_proto_rawDesc = nil
	file_joker_proto_goTypes = nil
	file_joker_proto_depIdxs = nil
}
